version: '2'
networks:
  basic:
services:
  world:
    container_name: world
    image: sayhello
    ports:
      - "9000:8080"
    volumes:
      - /Users/guozhuang/docker/gin/src/network:/go/src/SayHello:rw
    networks:
      - basic